version: '3'

services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: root
    ports:
      - "3306:3306"

  backend:
    image: aftas-backend
    ports:
      - "8080:8080"
    depends_on:
      - mysql

  frontend:
    image: aftas-frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend
